"""meal with user_id

Revision ID: b03de9914f81
Revises: 6fbf3631289b
Create Date: 2018-04-05 11:54:46.307693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b03de9914f81'
down_revision = '6fbf3631289b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'meal', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meal', type_='foreignkey')
    op.drop_column('meal', 'user_id')
    # ### end Alembic commands ###
